services:
  - type: web
    name: edumosaic-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edumosaic-db
          property: connectionString

databases:
  - name: edumosaic-db
    databaseName: edumosaic_db
    user: edumosaic_db_user